version: '3'

networks:
  td2net:
    driver: bridge

services:
  laboratory:
    build: ./docker/
    image: um/td2lab
    container_name: td2lab
    hostname: td2lab
    command: tail -n 50 -F /home/dev/workspace/docs/labFreeRTOS.md
    volumes:
      - .:/home/dev/workspace
    networks:
      - td2net
